### ISSUE TITLE
Model on same dir doesn't work

### ISSUE THREAD

**Issue by ManuLinares** [ideasman42/nerd-dictation#1]
I have to copy the model to "~/.config/nerd-dictation", it doesn't test for the "model" folder on the script dir.

**Comment by ideasman42** [comment]
Using the same directory as the script is error prone as the script may be copied into a shared bin directory in the future.

So I have removed this functionality, instead the default directory is used (as you have found), all the directory must be explicitly past.

I think this is the least error prone way of referencing the language model so users are not running into situations where it is not found and they aren't sure why.

See: 95304092e057db3dc9a8cb47f4d407b051f9c607
