### ISSUE TITLE
Add Italian language

### ISSUE THREAD

**Issue by albanobattistella** [ideasman42/nerd-dictation#105]
HI,
thanks for your great app.
Is possible to add commands/langage in italian?
Thank you.
Regards,
A.

**Comment by pancaek** [comment]
https://alphacephei.com/vosk/models/vosk-model-it-0.22.zip is the italian language model

**Comment by albanobattistella** [comment]
> https://alphacephei.com/vosk/models/vosk-model-it-0.22.zip is the italian language model

Thanks!
Is possible to add a simple UI?
thanks again for a great app.
Regards.
A.

**Comment by papoteur-mga** [comment]
I wrote elograf, on github, to have a GUI.
Translations are maanged on transifex/Mageia
