### ISSUE TITLE
--output STDOUT only sends output after dictation ends

### ISSUE THREAD

**Issue by jtara1** [ideasman42/nerd-dictation#109]
Is this the intention or a bug?

```
./nerd-dictation begin \
  --numbers-as-digits \
  --numbers-no-suffix \
  --output STDOUT
```

**Comment by jtara1** [comment]
I noticed it can delete many words to retype them when using the default `--output`. I'm guessing this is a feature of vosk with support for the retyping through xdotool.

This could then mean that the answer to my question is its the intended way it works as you can't change what's already sent to stdout.

**Comment by jtara1** [comment]
The startup time loading an improved bigger model is about 7s so calling begin and end on the dictation process is a little annoying if I just want intermittent results.

**Comment by jtara1** [comment]
I just wanted a more programmatic way (i.e.: dictation piped to a socket) to work with the output of the live dictation. Maybe it's worth exploring the use of nerd-dictation in a VM or re-evaluating the output of vosk to find the best way to work with it.

**Comment by isidroas** [comment]
I also see this. I think that it is not documented in the cli --help.
