### ISSUE TITLE
Initial caps

### ISSUE THREAD

**Issue by MikeyBeez** [ideasman42/nerd-dictation#11]
Is there an easy way to fix missing initial caps?  Maybe a keystroke?

**Comment by ideasman42** [comment]
Did you try `--full-sentence` optionally with `--punctuate-from-previous-timeout` ?

**Comment by MikeyBeez** [comment]
No I didn't because I'm a lazy idiot.  Sorry.  These work fine. Thank you for writing this.  I use it every day now.  Between this and Copilot, I don't need to type any more. :)

**Comment by MikeyBeez** [comment]
Thanks so much!
