### ISSUE TITLE
Current status (activated, suspended, etc.)

### ISSUE THREAD

**Issue by agzam** [ideasman42/nerd-dictation#117]
I want to bind the `begin` and `end` to the same button to simplyfy toggling the dictation on and off, but the app doesn't seem to provide a way to check for the current state of dictation, or does it?

**Comment by agzam** [comment]
Nevermind, I just discovered `begin --cookie` option. Apologies for the noise. Closing this now.

**Comment by DovieW** [comment]
@agzam Can you please explain how you use `begin --cookie` to toggle?

**Comment by DovieW** [comment]
I see. This is the documentation: `--cookie FILE_PATH Location for writing a temporary cookie (this file is monitored to begin/end dictation)`

So you can just check for that file I assume. `pgrep -f "nerd-dictation begin"` also should work.
