### ISSUE TITLE
use pypy3 to speed up desktop lockup

### ISSUE THREAD

**Issue by Corallus-Caninus** [ideasman42/nerd-dictation#12]
this should use pypy3 to launch nerd-dictation instead of python3.  i got pypy3 to work but i did not implement as an executable like python3.  it seemingly gives a performance increase although i still have some lock up when i wait for the text to process.  another alternative is to use numba but i haven't looked into this or whether it is possible nor have i profiled the code to see where this would be most appropriate. 

 thank you i wrote this issue using nerd dictation with minor editing.

**Comment by ideasman42** [comment]
A few things:

- Is VOSK compatible with a pypy3? (it uses the C extension API).
- Since python isn't doing any significant computation, I would be surprised if there was much difference CPython3 & PyPy3.

**Comment by ideasman42** [comment]
No response in over a week, closing.
