### ISSUE TITLE
Question: delete space in front of "." or "," 

### ISSUE THREAD

**Issue by iradraconis** [ideasman42/nerd-dictation#21]
Hi. I have a question that I cannot find the answer to, since I am a beginner in Python. So I use a german model for nerd-dication. Full sentences do not work here, so I have to dictate "Komma" or "Punkt" for comma and full-stop. Now I have configured the user configuration file that those two words are replaced with "," and ".". I need to delete the space in front of those characters. How can I achieve this via the configuration file? Your help is much appreciated.

By the way I solved the "proper noun" thing for me, as I integrated spacy and let it check for nouns and then capitalize the word. It is a bit slow then, but it works.

Thanks for this really great tool!

**Comment by iradraconis** [comment]
never mind, I sorted it out by myself :)

**Comment by mekb-turtle** [comment]
how did you do this?
