### ISSUE TITLE
Using listen on / off to begin / end dictation

### ISSUE THREAD

**Issue by patricksebastien** [ideasman42/nerd-dictation#24]
Instead of using a keyboard shortcut, I would like to use 2 keywords to begin and end dictation. Meaning that nerd-dictation will always listen to microphone and when recognised: listen on = start typing and listen off, stop typing (xdotool).

How to implement that?

**Comment by ideasman42** [comment]
Does this example do what your looking for?

https://github.com/ideasman42/nerd-dictation/blob/c94f8c4835743cd6920b7552645c721e8d54fc89/examples/begin_end_commands/nerd-dictation.py

**Comment by patricksebastien** [comment]
Exactly what I needed! Thank you so much :+1:
