### ISSUE TITLE
Russian input lags entire interface

### ISSUE THREAD

**Issue by scaledteam** [ideasman42/nerd-dictation#32]
Russian input lags entire interface. But some programs (Blender for example) don't lag at all (also Blender usually launched in fullscreen). English input works fine. Model: "vosk-model-small-ru-0.22"

**Comment by scaledteam** [comment]
Strange, but in previous tests keyboard layout didn't make any difference, now works fine with russian keyboard layout and lags with english layout. Also, input is accurate in both lauguages, no matter what layout was enabled.

**Comment by scaledteam** [comment]
Ok, after day of testing i can definely tell that russian input is laggy. In some applications it fast, in others - very slow. Layout makes huge difference, but it still depends on speed of speech, application, and anyway, it much laggier than english input.

**Comment by ideasman42** [comment]
Hi, I doubt this is an issue with `nerd-dictation`. Although there may be a workaround I could implement.
It seems likely this is an issue with `xdotool` - can you test if other text entered directly to `xdotool` has this problem?

If so, the bug can be reported upstream.

**Comment by scaledteam** [comment]
Yes, this is xdo problem. Even python3-xdo module have same issue. Maybe you have some idea, how to do input another way?
```
import time
import xdo
time.sleep(3);xdo.xdo().type("Проверка набора любого русского текста.")
```

**Comment by ideasman42** [comment]
Okay, best report this upstream then, closing.
