### ISSUE TITLE
Stream error: No such entity

### ISSUE THREAD

**Issue by mekb-turtle** [ideasman42/nerd-dictation#33]
Hi, when starting nerd dictation, I get the following message
Stream error: No such entity
When speaking, no text shows.

**Comment by ideasman42** [comment]
Could you try recording directly from `parec` ?

`parec --format=s16le --rate=44100 --file-format=wav test.wav`

If you get the same error, you can troubleshoot the problem on the command line.

See similar issue: https://github.com/mpv-player/mpv/issues/1632

**Comment by mekb-turtle** [comment]
that command still gives the same error, so i assume it's `parec`'s fault

**Comment by ideasman42** [comment]
Right, you may be able to specify a device, e.g. I use `--device=alsa_input.usb-M-Audio_AIR_192_4-00.analog-stereo`, see `pacmd list-sinks | grep "name:"`

**Comment by mekb-turtle** [comment]
where do i put the `--device` argument?

**Comment by ideasman42** [comment]
This is an example command:

```
nerd-dictation \
    begin \
    --vosk-model-dir=/scratch/src/vosk-api/python/example/model \
    --cookie=/scratch/tmp/stt.cookei \
    --pulse-device-name=alsa_input.usb-M-Audio_AIR_192_4-00.analog-stereo \
    --delay-exit=0.1
```

**Comment by mekb-turtle** [comment]
that still gives the same error, replacing the device name with my one from `pacmd list-sinks | grep "name:"`

**Comment by ideasman42** [comment]
If you manage to get `parec --format=s16le --rate=44100 --file-format=wav test.wav` working, then `nerd-dictation` should be able to be supported too.

**Comment by mekb-turtle** [comment]
adding `--pulse-device-name=alsa_input.pci-0000_00_1b.0.analog-stereo` to nerd-dictation works, `pacmd list-sinks | grep "name:"` listed the outputs, not the inputs
