### ISSUE TITLE
'huh' outputted after exiting

### ISSUE THREAD

**Issue by makeworld-the-better-one** [ideasman42/nerd-dictation#34]
Hello, thanks for creating this project! Very cool.

I've noticed that `huh` is outputted after I stop nerd-dictation from running. Maybe outputted twice? I'm using the small English model from the install instructions.

![image](https://user-images.githubusercontent.com/25111343/149870532-156b7f66-cdc9-4e41-b6d8-abcafcbe3db7.png)

**Comment by ideasman42** [comment]
Hi, I can't redo this - could you try run and dictate into separate windows to check if `nerd-dictation` is outputting to the `stdout`?

**Comment by makeworld-the-better-one** [comment]
## Testing

Is this reproducible? What causes it?

### Test 1
- Running `nerd-dictation begin` in one terminal
- Opening a text editor in another terminal, dictation works
- Close text editor
- Run `nerd-dictation end` in the second terminal

Result: no `huh` output.

### Test 2

Same as 1, but with `nerd dictation begin &`

Result: no huh

### Test 3

- Running `nerd-dictation begin &` in one terminal
- Opening a text editor in another terminal, dictation works
- Close text editor
- Run `nerd-dictation end` in the **first** terminal

Result: no huh

### Test 4

- Running `nerd-dictation begin &` in one terminal
- Run `nerd-dictation end` in the same terminal

This is the same test as in my original comment.

Result: no huh

## Conclusion

I cannot reproduce this issue anymore. I used to be able to reproduce it, it wasn't a one-off when I filed the issue.

Maybe what happened is that I was saying the word `huh`, or my keyboard or something in my environment at the time was being picked up as that word. And there was a delay in typing it out, so it appeared after nerd-dictation stopped. I am not sure.

If you'd like to close that issue that's fine. I'll comment here if I can reproduce this at some point, or it starts occurring again.

**Comment by ideasman42** [comment]
There seems to be issues where some of the models are injecting `the` or `huh` or other words much more often then they should.

I think the solution here is to:

- Record speech of reasonably good quality.
- Pass this to VOSK.
- Confirm the VOSK+Model configuration is giving bad results.

I'd like to add support for `nerd-dictation` to accept `stdin`, allowing something like.

```
cat example.wav | nerd-dictation begin --model=test-model --stdout
```

This could then be used for reproducible tests.

**Comment by maximstewart** [comment]
I can attest that this happens to me. It'll often dump "the"  after saying something. This happens so far in any input field that I've tried. Lowering my input volume seems to help
 the
 i can attest that this happens to me. it will often

**Comment by maximstewart** [comment]
the the the
