### ISSUE TITLE
No keystrokes appear in LibreOffice Writer

### ISSUE THREAD

**Issue by xenotropic** [ideasman42/nerd-dictation#37]
With some sort of recent upgrade either Ubuntu or LibreOffice the I have noticed that I cannot use nerd-dictation in LibreOffice writer.  No text appears.  nerd-dictation works fine with chrome or thunderbird windows. It did not used to be this way. I have upgraded from  ubuntu 18 to 21.10  recently,  so perhaps there was some sort of change with regard to that period maybe there's some sort of security policy that prevents simulated keystrokes? Just a guess. Libreoffice is 7.2.3.2.

**Comment by ideasman42** [comment]
Hi, I can't redo this error (libreoffice-fresh-7.2 works fine for me on ArchLinux).

this is almost certainly an issue with `xdotool` as nerd-dictation just calls out to this utility.

All I can suggest is to investigate why libreoffice doesn't accept xdotool's output.

Try this in the command line:

```
sleep 3 && xdotool type "Hello World"
```
Run this command in a terminal, move your cursor over the libreoffice window and check if the text is typed in as expected.

If not you could report a bug to libreoffice.

**Comment by xenotropic** [comment]
Yes, that xdotool fails on command line. I'll report to LO. Thanks for taking the time to respond.

**Comment by xenotropic** [comment]
For posterity, noting here that I reported this as [LibreOffice bug 146889](https://bugs.documentfoundation.org/show_bug.cgi?id=146889)

**Comment by xenotropic** [comment]
This is an X vs Wayland issue per LO. xdotool is x-only (guess that's the "x"). LO runs as Wayland native. Hence, no xdotool input in LO windows. LO says (in the bug linked in last comment) "nerd-dictation could try these alternatives: https://github.com/ReimuNotMoe/ydotool https://github.com/atx/wtype"

No expectation from me personally that you'll do that, but just FYI for answering the questions of others, etc.

**Comment by ideasman42** [comment]
Ah, in that case we should support an alternative as you suggest. I'm open to this but don't have short term plans to implement it.

**Comment by LibreroGit** [comment]
Hola a todos, quiero compartir mi experiencia con nerd-dictation. Lo instalé porque por un accidente, quedé temporalmente con solo una mano habilitada para escribir, así que cuando encontré esta utilidad, la instalé hasta que funcionó perfectamente en Ubuntu 20.04 y podía escribir en Gedit y en Writer. Ahora he actualizado a Ubuntu 22.04 y ya no puedo escribir en Gedit ni en Writer. Si lo hace en whatsApp y en Google. Tampoco escribe en Thunderbird. Si me informan que es lo que debo agregar/quitar/hacer  para que funcione, estaré muy agradecido.  El texto hasta aquí escrito fue realizado desde el teclado, lo que sigue es un dictado de mi voz. Por supuesto probé con el comando sleep 3 y funciona, sólo donde está funcionando la aplicación de forma natural.
