### ISSUE TITLE
request: add an icon to known when it is active

### ISSUE THREAD

**Issue by Lunatik00** [ideasman42/nerd-dictation#44]
I know this might be beyond the simplicity of this program, but it would be awesome to have at least an icon in the taskbar, that way i could put the timeout in the shortcut and know when it has timed out, it would be a quality of life improvement, although it is non essential.

**Comment by ideasman42** [comment]
nerd-dictation is a command line application, I'd rather keep UI enhancements separate projects - https://github.com/papoteur-mga/elograf for example.

Since this uses a file to start/end dictation it shouldn't be too difficult to have a UI element in the status-bar monitor a file.

Closing.
