### ISSUE TITLE
looong processing time

### ISSUE THREAD

**Issue by squintarelli** [ideasman42/nerd-dictation#47]
Hello,

after starting recognition, for any short sentence to be recognized, it takes _ages_ before producing any output.
(by ages, I mean from 30 to 90 seconds; in the meantime, the computer is frozen). 
after getting the first output the terminal starts responding again (although not fluidly) and I'm able to stop it.

I am running Ubuntu 20.04.1 on a i7 .3GHz 8 core CPU with 15.4 GB RAM

any suggestion is highly appreciated..

**Comment by ideasman42** [comment]
Try using different models, they vary widely in the amount of processing time.

Closing as this isn't something than is practical to solve on our end, see:
https://alphacephei.com/vosk/
