### ISSUE TITLE
Error during installation on Arch Linux

### ISSUE THREAD

**Issue by FilipeMarch** [ideasman42/nerd-dictation#54]
I am on Arch Linux. After opening a terminal and typing `pamac search vosk`
![image](https://user-images.githubusercontent.com/23220309/165557161-9cde45f2-48da-448a-b112-8d10e05c2acc.png)

I execute `pamac install python-vosk` and then I get the error `Failed to compile vosk-api`
![image](https://user-images.githubusercontent.com/23220309/165557465-cbe91aa4-c64a-4f61-b2a2-568d28806a41.png)

The same error happens if I execute `pamac install nerd-dictation-git`

Not a super big issue because I have been able to install the code successfully by following the tutorial. But I wonder why pamac is not working for installing these packages.

**Comment by ideasman42** [comment]
This is a problem with the `python-vosk` package on AUR, reported here: https://aur.archlinux.org/pkgbase/vosk-api#comment-862994

Closing as it's not something that can be resolved here.
