### ISSUE TITLE
Feature request: single word with time stamp

### ISSUE THREAD

**Issue by CommandMaster** [ideasman42/nerd-dictation#56]
Usecase: with audiofile as input 

Example flag: --single-word-timestamp

Output: word: hi beginning:1.54,6 end: 1.55,3

**Comment by ideasman42** [comment]
What would these time-stamps be used for?

**Comment by CommandMaster** [comment]
> I'm not sure of the use case for this, what would you do with this information?

selectively analysing audio of videos (exporting event-word out of long audio)
Usecase: importing output, of function, and then automatically trimming a video on timestamp of the event-word

**Comment by ideasman42** [comment]
If your doing your own text/audio analysis I'd consider this out of scope for general dictation, in this case the VOSK-API could be used directly.
