### ISSUE TITLE
Adding simple built-in support for a config and model per language

### ISSUE THREAD

**Issue by NathanLovato** [ideasman42/nerd-dictation#58]
I would like to have support for easily having a separate script and model for languages other than English. I'd gladly contribute this if it's a feature you would like in nerd-dictation.

Currently, you have a config folder where you can place a model, and a Python file nerd-dictation will use by default.

The idea would be to add a new command-line option to choose a config subfolder, e.g. `--config-subfolder=fr`. In that case, nerd-dictation would try to find the model and the Python file in `.config/nerd-dictation/fr/` instead of `.config/nerd-dictation/`.

This would allow users to have a configuration per language (or, I dunno, for different use cases) without adding complexity to the program.

Is this something you'd like to have in nerd-dictation? If so, Is there anything you would like me to do to contribute this? Documentation, specific cli option name, example configuration in another language...

**Comment by ideasman42** [comment]
Is there a significant advantage to this over passing in a `--config` file? e.g. `--config=$HOME/.config/nerd-dictation/nerd-dictation.py` ?

I suppose we could have a `--config-basename` argument, so you could simply write `--config-basename=nerd-dictation-fr.py` without the full path but this doesn't seem like such a benefit over the full path.

**Comment by NathanLovato** [comment]
No, the advantage's not significant. Actually sorry, I just forgot you could already do that!
