### ISSUE TITLE
High usage of CPU

### ISSUE THREAD

**Issue by papoteur-mga** [ideasman42/nerd-dictation#6]
When executing nerd-dictation with or without --continuous option, the load of CPU is still high, of about one complete core.
When stopping the execution with keyboard interrupt, I got always interruption in function exit_fn.
If I try to add:
```
    time.sleep(PROGRESSIVE_CONTINUOUS_SLEEP_WHEN_IDLE)
```
just before calling` return 0`, the CPU usage is low, without big impact on accuracy.

**Comment by ideasman42** [comment]
This could be said to a default of `PROGRESSIVE_CONTINUOUS_SLEEP_WHEN_IDLE`, but it would be nice if it was tunable, personally I prefer some responsiveness at the cost of some CPU time.

**Comment by papoteur-mga** [comment]
Great fix, thanks. :-)
