### ISSUE TITLE
ydotool alternative: dotool

### ISSUE THREAD

**Issue by JohnGebbie** [ideasman42/nerd-dictation#68]
Hello, I wrote a ydotool alternative called [dotool](https://git.sr.ht/~geb/dotool) and think it could help.
It is designed to run without root permissions and the daemon is optional.

I wrote it because ydotool and all the required patching was stopping my program (https://numen.johngebbie.com) that depended on it getting packaged on distros.

All the best,

John

EDIT: I have got dotool packaged on Void Linux, hopefully it will be packaged elsewhere soon.

**Comment by ideasman42** [comment]
Hi John, thanks for letting me know. While I didn't try it - Integrating this seems reasonable / worthwhile.
So a PR that does so would be welcome, otherwise I'll look into this when I get some time (if nobody else does first).

**Comment by ideasman42** [comment]
dotool is now supported, closing.
