### ISSUE TITLE
What configuration script and nerd-dictation options did you use for your youtube video?

### ISSUE THREAD

**Issue by KJ7LNW** [ideasman42/nerd-dictation#77]
I saw your video and wondered how you invoked `nerd-dictation` for that example?  Did you have any special .py configuration or command line options?

- https://www.youtube.com/watch?v=T7sR-4DFhpQ

**Comment by ideasman42** [comment]
Hi, I can't recall the details, this was early on in nerd-dictations development.

Closing as I don't think it helps to keep this task open.
