### ISSUE TITLE
Launcher in systray

### ISSUE THREAD

**Issue by papoteur-mga** [ideasman42/nerd-dictation#8]
I have created for my usage a launcher which displays an icon in the systray and on which action launches or stop nerd-dictation.
What is working uses PyQt and the icon acts as a toggle button. Memory impact seems to be 17 Mo.
I have also tried pystray. It works but with some caveats: in my LXQt, the icon is not displayed, but a gear instead. It acts by displaying a contextual menu, thus needs two actions, I did find how to catch a single click on the icon. And on a recent LXQt, it doesn't work at all because of an error on DBus. Memory impact seems to be 13 Mo. 
I didn't check the size of what is pulled as requirement.
This is not yet ready for large usage, because I have no installation system, and paths are hardcoded.
But do you mean it's something to add to nerd-dictation or to put in another place ?

**Comment by ideasman42** [comment]
Thanks for letting me know, I'd assume any tool that can control the lifespan of a process could be setup to use a system-tray utility like this.

I'd like to keep nerd-dictation a simple utility, even so, other utilities can still be included or optionally bundled.

For now, I don't think it's important to figure out if including it in the same repository or not is important. Once it's finished & working, it can be bundled / or be part of a separate repository.

**Comment by papoteur-mga** [comment]
Hello,
This tool is now available.
https://github.com/papoteur-mga/elograf

**Comment by ideasman42** [comment]
Thanks, added an "Other Software" section to the readme and linked.
