### ISSUE TITLE
Add a flag to remove NSFW words

### ISSUE THREAD

**Issue by Kern3l** [ideasman42/nerd-dictation#99]
Hey! :slightly_smiling_face: I'm using your amazing QoL improvement for work. Sometimes if it mishears me it produces some other word. It happened to me to include a scrambled "fcuk". Fortunately not during a meeting :laughing: I'd love to be able to use it during meetings to speed up any writing down that is typically a bottleneck, but I'd like to not end up with NSFW situation :smile:

**Comment by ideasman42** [comment]
Hey, this seems like something that could be handled by a user configuration which replaces or removes NSFW words.

This should be fairly easy to do, check the current examples, it only requires word replacement which is quit simple to do.

**Comment by ideasman42** [comment]
Closing as this can be handled as part of user configuration, further it would mean having a list of NSFW words which is unlikely to be generally agreed on as it differs between English speaking countries. So I rather let users handle their own word-replacements.
